### ISSUE TITLE
Make readme file

### ISSUE THREAD

**Issue by GeorgeKirm** [GeorgeKirm/OpenMP-MPI-project#13]
project needs readme file

**Comment by vamartid** [comment]
@alouvoul  you should give it a try :)

**Comment by alouvoul** [comment]
Να πεθάνεις!

**Comment by rigopoui** [comment]
Hello, 
  I want  to write a specification document for your project. Would you include it in the project if I sent it to you? I promise it's not for a uni course, I am genuinely interested in specification documents.

**Comment by GeorgeKirm** [comment]
Of course kind sir! Every contribution from the open source community is welcome!
